### ISSUE TITLE
Internal server error: sqlite3.OperationalError) 

### ISSUE THREAD

**Issue by Immunoking** [Merck/BioPhi#60]
I am running a simplified biophi server on my machine. Once I start a humanization project I get the following error on the localhost page: 

Error: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8)

Could somebody help me out how to get rid of this issue?

**Comment by Immunoking** [comment]
Fixed this issue by rewrite the code correclty

**Comment by SolaceUser** [comment]
Attempted the initial install using python with Conda(BioConda)

I recieved the error:
ResolvePackageNotFound:
- hmmer[version='>=3.1'] 

There is an open Git issue for this dependancy error: 
https://github.com/Merck/BioPhi/issues/54

Attempted to resolve the issue but was unable to find a compatible version of hmmer


Upon running the docker container received the error:
Error: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8)

Attempted to use the latest version of the biocontainer in the repo 
quay.io/biocontainers/biophi:1.0.9--pyhdfd78af_2
Same result.

Is there any documentation as to how this issue was resolved?
